--TABLO OLUÞTURMA
CREATE TABLE [playground].[dbo].[datapioneers_cities] (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    city NVARCHAR(50),
    district NVARCHAR(50),
    must_taste_foods NVARCHAR(250),
    places_to_visit NVARCHAR(250)
);

--OLUÞTURULAN TABLOMUZU GÖRME
select * from [playground].[dbo].[datapioneers_cities] 


alter table datapioneers_master_data
add Seasons_Winter nvarchar(25)


alter table datapioneers_master_data
add Daily_Room_Rate decimal(15,2)

--ÝNSERT BLOKLARI
/*
insert into datapioneers_cities (city, district, must_taste_foods, places_to_visit)
values
('Adana', 'Seyhan', 'Adana Kebap', 'Seyhan Baraj Golu'),
('Adana', 'Yüreðir', 'Bici Bici', 'Misis Mozaik Müzesi'),
('Afyon', 'Ýhsaniye', 'Buhara Kebabý', 'Ayazini Kaya Mezarlarý'),
('Afyon', 'Merkez', 'Afyon Sucugu', 'Afyon Kalesi'),
('Afyon', 'Sandýklý', 'Patlican Boregi', 'Sandikli Kaplicalari'),
('Afyon', 'Yaylabaðý', 'Manta', 'Frig Vadisi'),
('Aðrý', 'Merkez', 'Abdigor köftesi', 'Ýshak Paþa Sarayý'),
('Amasya', 'Merkez', 'Amasya Tas Firin Pidesi', 'Amasya Kalesi'),
('Ankara', 'Ayaþ', 'Ayaþ dut pekmezi', 'Ayaþ Kaplýcalarý'),
('Ankara', 'Çankaya', 'Ankara Tavasi', 'Atakule'),
('Ankara', 'Güdül', 'Güdül Tava', 'Sorgun Göleti ve Tabiat Parký'),
('Ankara', 'Haymana', 'Haymana yoðurdu', 'Haymana Kaplýcalarý'),
('Ankara', 'Kýzýlay', 'Tavuk Doner', 'Kizilay Meydani'),
('Ankara', 'Kýzýlcahamam', 'Bazlama', 'Soðuksu Milli Parký'),
('Ankara', 'Merkez', 'Ankara tava', 'Anýtkabir'),
('Antalya', 'Aksu', 'Aksu Yogurt Corbasi', 'Perge Antik Kenti'),
('Antalya', 'Alanya', 'Sis Kofte', 'Alanya Kalesi'),
('Antalya', 'Belek', 'Kofte', 'Aspendos Antik Tiyatrosu'),
('Antalya', 'Döþeme altý', 'Kölle (buðday, nohut, fasulye karýþýmý)', 'Termessos Antik Kenti'),
('Antalya', 'Finike', 'Finike portakalý ile yapýlan reçeller', 'Limyra Antik Kenti'),
('Antalya', 'Gazipasa', 'Yörük kebabý', 'Selinus Antik Kenti'),
('Antalya', 'Kas', 'Akdeniz Baligi', 'Kaputas Plaji'),
('Antalya', 'Kemer', 'Kemer Kebabi', 'Phaselis Antik Kenti'),
('Antalya', 'Konyaalti', 'Girit Mezeleri', 'Konyaalti Plaji'),
('Antalya', 'Kumluca', 'Portakal', 'Olimpos Antik Kenti'),
('Antalya', 'Lara', 'Lara Boregi', 'Lara Plaji'),
('Antalya', 'Manavgat', 'Piyaz', 'Manavgat Selalesi'),
('Antalya', 'Merkez', 'Antalya Dondurmasi', 'Kaleici'),
('Antalya', 'Muratpasa', 'Hibes', 'Ataturk Parki'),
('Antalya', 'Serik', 'Serik Kebabi', 'Zeytintasi Magarasi'),
('Antalya', 'Side', 'Tahinli Piyaz', 'Side Antik Kenti'),
('Artvin', 'Merkez', 'Artvin Kebabi', 'Artvin Kalesi'),
('Aydin', 'Didim', 'Didim Sarmasi', 'Milet Antik Kenti'),
('Aydin', 'Germencik', 'Germencik Kuzu Tandigi', 'Aphrodisias Antik Kenti'),
('Aydin', 'Kusadasi', 'Seafood', 'Kusadasi Milli Park'),
('Aydin', 'Söke', 'Cop Sis', 'Priene Antik Kenti'),
('Balýkesir', 'Ayvalýk', 'Ayvalik Tostu', 'Cunda Adasi'),
('Balýkesir', 'Bandýrma', 'Peynirli Borek', 'Bandirma Arkeoloji Muzesi'),
('Balýkesir', 'Burhaniye', 'Zeytinyaðlý enginar', 'Ören Plajý'),
('Balýkesir', 'Edremit', 'Zeytinyagli Sarma', 'Kaz Daglari'),
('Balýkesir', 'Erdek', 'Balýkesir pidesi', 'Kyzikos Antik Kenti'),
('Balýkesir', 'Gömeç', 'Zeytin ezmesi', 'Taþköy Doða Parký'),
('Balýkesir', 'Güre', 'Höþmerim tatlýsý', 'Güre Kaplýcalarý'),
('Balýkesir', 'Karesi', 'Balýkesir mantýsý', 'Karesi Bey Türbesi'),
('Balýkesir', 'Merkez', 'Susurluk tostu', 'Balýkesir Saat Kulesi'),
('Balýkesir', 'Sarmýsaklý', 'Papalina Balýðý', 'Sarýmsaklý Plajý'),
('Bilecik', 'Merkez', 'Bilecik güveci', 'Þeyh Edebali Türbesi'),
('Bolu', 'Göynük', 'Kýzýlcýk tarhana çorbasý', 'Göynük Zafer Kulesi'),
('Bolu', 'Kartalkaya', 'Sucuk Ekmegi', 'Kartalkaya Kayak Merkezi'),
('Bolu', 'Merkez', 'Kiymali Gozleme', 'Abant Golu'),
('Bolu', 'Mudurnu', 'Mengen pilavý', 'Yýldýrým Bayezid Cami'),
('Burdur', 'Merkez', 'Burdur Sis', 'Salda Golu'),
('Bursa', 'Ýnegöl', 'Inegol Koftesi', 'Inegol Kent Muzesi'),
('Bursa', 'Ýznik', 'Ýznik çinili mantý', 'Ýznik Gölü'),
('Bursa', 'Merkez', 'Ýskender kebap', 'Tophane Saat Kulesi'),
('Bursa', 'Osmangazi', 'Kestaneli Pilav', 'Tarihi Kapali Carsi'),
('Çanakkale', 'Ayvacýk', 'Zeytinyagi', 'Assos Antik Kenti'),
('Çanakkale', 'Çan', 'Sarýmsaklý Kuzu Tandýrý', 'Troya Antik Kenti'),
('Çanakkale', 'Merkez', 'Peynir Helvasi', 'Canakkale Sehitligi'),
('Çorum', 'Merkez', 'Corum Leblebisi', 'Alacahoyuk'),
('Denizli', 'Merkez', 'Denizli kebabý', 'Pamukkale'),
('Denizli', 'Merkezefendi', 'Kuyu kebabý', 'Çamlýk Ormaný'),
('Denizli', 'Pamukkale', 'Pamuk Seker', 'Pamukkale Travertenleri'),
('Denizli', 'Sarayköy', 'Kabak tatlýsý', 'Karahayýt Kaplýcalarý'),
('Diyarbakýr', 'Baðlar', 'Kaburga dolmasý', 'Hevsel Bahçeleri'),
('Düzce', 'Akçakoca', 'Misir Ekmegi', 'Ceneviz Kalesi'),
('Düzce', 'Kaynaþlý', 'Düzce Kebabý', 'Güzeldere Þelalesi'),
('Edirne', 'Merkez', 'Ciger Tava', 'Selimiye Camii'),
('Erzurum', 'Palandöken', 'Cag Kebabi', 'Palandoken Kayak Merkezi'),
('Eskiþehir', 'Merkez', 'Çibörek', 'Odunpazarý'),
('Eskiþehir', 'Odunpazarý', 'Ciborek', 'Odunpazari Evleri'),
('Eskiþehir', 'Tepebaþý', 'Eskisehir Ciborek', 'Eskisehir Sazova Parki'),
('Gaziantep', 'Þahinbey', 'Beyran çorbasý', 'Zeugma Mozaik Müzesi'),
('Gaziantep', 'Þehitkamil', 'Baklava', 'Gaziantep Zeugma Muzesi'),
('Giresun', 'Dereli', 'Kiraz kavurmasý', 'Kuzalan Þelalesi'),
('Hatay', 'Antakya', 'Kunefe', 'Habib-i Neccar Camii'),
('Hatay', 'Erzin', 'Tepsi kebabý', 'Erzin Kaplýcalarý'),
('Hatay', 'Ýskenderun', 'Künefe', 'Ýskenderun Sahili'),
('Isparta', 'Merkez', 'Isparta kebabý', 'Gölcük Krater Gölü'),
('Istanbul', 'Ataþehir', 'Meze Tabaðý', 'Kadýköy Çarþýsý'),
('Istanbul', 'Avcýlar', 'Kumpir', 'Avcýlar Sahili'),
('Istanbul', 'Baðcýlar', 'Istanbul Simidi', 'Kemerburgaz Kent Ormani'),
('Istanbul', 'Bakýrköy', 'Midye dolma', 'Bakýrköy Botanik Parký'),
('Istanbul', 'Baþakþehir', 'Sarma', 'Baþakþehir Millet Bahçesi'),
('Istanbul', 'Bayrampaþa', 'Islak Hamburger', 'Bayrampaþa Parký'),
('Istanbul', 'Beþiktaþ', 'Doner', 'Dolmabahce Sarayi'),
('Istanbul', 'Beylikdüzü', 'Beylikdüzü pizza', 'Beylikdüzü Sahili'),
('Istanbul', 'Beyoðlu', 'Kokorec', 'Galata Kulesi'),
('Istanbul', 'Büyükçekmece', 'Lüfer balýðý', 'Büyükçekmece Gölü'),
('Istanbul', 'EyupSultan', 'Osmanli Serbeti', 'Pierre Loti Tepesi'),
('Istanbul', 'Fatih', 'Boza', 'Sultanahmet Camii'),
('Istanbul', 'Güngören', 'Ýçli köfte', 'Güngören Parký'),
('Istanbul', 'Kadýköy', 'Kadýköy böreði', 'Moda Sahili'),
('Istanbul', 'Mahmutbey', 'Kavurma', 'Mahmutbey Ormaný'),
('Istanbul', 'Maltepe', 'Sandvic', 'Maltepe Sahili'),
('Istanbul', 'Pendik', 'Saray Kebabý', 'Pendik Sahili'),
('Istanbul', 'Þile', 'Þile balýðý', 'Aðva'),
('Istanbul', 'Silivri', 'Silivri yoðurdu', 'Silivri Kalesi'),
('Istanbul', 'Þiþli', 'Ayran', 'Bomontiada'),
('Istanbul', 'Ümraniye', 'Ümraniye döner', 'Çamlýca Tepesi'),
('Istanbul', 'Üsküdar', 'Lahmacun', 'Kiz Kulesi'),
('Izmir', 'Balçova', 'Balçova kestane þekeri', 'Teleferik'),
('Izmir', 'Bayrakli', 'Bayraklý mantýsý', 'Sasalý Doðal Yaþam Parký'),
('Izmir', 'Çesme', 'Cesme Kumru', 'Cesme Kalesi'),
('Izmir', 'Dikili', 'Ege otlarý salatasý', 'Dikili Plajý'),
('Izmir', 'Foça', 'Foça midyesi', 'Foça Antik Kenti'),
('Izmir', 'Gaziemir', 'Gaziemir Uzumu', 'Optimum AVM'),
('Izmir', 'Gümüldür', 'Gümüldür incir tatlýsý', 'Gümüldür Ormanlarý'),
('Izmir', 'Karsiyaka', 'Karþýyaka lokmasý', 'Karþýyaka Sahili'),
('Izmir', 'Konak', 'Lokma', 'Konak Meydani'),
('Izmir', 'Menderes', 'Izgara köfte', 'Bostanlý Ýskelesi'),
('Izmir', 'Merkez', 'Boyoz', 'Izmir Saat Kulesi'),
('Izmir', 'Narlidere', 'Müldür Kebabý', 'Karaburun'),
('Izmir', 'Özdere', 'Keskek', 'Ozdere Plaji'),
('Izmir', 'Seferihisar', 'Seferihisar Mandalina', 'Sigacik Kalesi'),
('Izmir', 'Selçuk', 'Enginar', 'Efes Antik Kenti'),
('Izmir', 'Urla', 'Sarýmsaklý mantý', 'Sinop'),
('Kars', 'Sarýkamýþ', 'Murtuga', 'Sarikamis Kayak Merkezi'),
('Kastamonu', 'Merkez', 'Kastamonu Tirit', 'Kastamonu Arkeoloji Müzesi'),
('Kayseri', 'Hacýlar', 'Mantý', 'Erciyes Daðý'),
('Kayseri', 'Kocasinan', 'Pastýrma', 'Gesi Baðlarý'),
('Kayseri', 'Melikgazi', 'Sucuk', 'Hunat Hatun Cami'),
('Kýrklareli', 'Demirköy', 'Pýrasa Sarmasý', 'Dupnisa Maðarasý'),
('Kýrþehir', 'Merkez', 'Kirsehir Corbasi', 'Kirsehir Kalesi'),
('Gazimaðusa', 'Gazimaðusa', 'Corek', 'Gazimagusa Kalesi'),
('Girne', 'Girne', 'Hellimli Pide', 'Karaoglanoglu Sehitligi'),
('Ýskele', 'Ýskele', 'Bafra Dondurmasi', 'Bafra Plaji'),
('Lefkoþa', 'Lefkoþa', 'Kibris Seftali Kebabi', 'Buyuk Han'),
('Kocaeli', 'Baþiskele', 'Tarator', 'Baþiskele Sahili'),
('Kocaeli', 'Darýca', 'Sarýmsaklý Yoðurtlu Mücver', 'Ballýkayalar Tabiat Parký'),
('Kocaeli', 'Ýzmit', 'Kandira Yogurdu', 'Saat Kulesi'),
('Kocaeli', 'Kartepe', 'Kartepe Corbasi', 'Kartepe Kayak Merkezi'),
('Konya', 'Karatay', 'Bamya çorbasý', 'Alaaddin Tepesi'),
('Konya', 'Selçuklu', 'Etli ekmek', 'Selçuklu Köþkü'),
('Kütahya', 'Merkez', 'Simit Tiridi', 'Kutahya Kalesi'),
('Malatya', 'Merkez', 'Kayýsý tatlýsý', 'Malatya Müzesi'),
('Manisa', 'Salihli', 'Odun köfte', 'Kurþunlu Kaplýcalarý'),
('Mersin', 'Bozyazý', 'Papalina Tava', 'Mamure Kalesi'),
('Mersin', 'Erdemli', 'Limonata', 'Kizkalesi'),
('Mersin', 'Merkez', 'Humus', 'Kushimoto Sokak'),
('Mersin', 'Mezitli', 'Kerebic', 'Kastabala Antik Kenti'),
('Mersin', 'Silifke', 'Tantuni', 'Silifke Kalesi'),
('Mersin', 'Toroslar', 'Arap kadayýfý', 'Yumuktepe Höyüðü'),
('Mersin', 'Yanýþlý', 'Yenisli Boregi', 'Tasucu Limani'),
('Mersin', 'Yeniþehir', 'Bulgur pilavý', 'Mersin Marina'),
('Mugla', 'Bodrum', 'Bodrum Doner', 'Bodrum Kalesi'),
('Mugla', 'Dalaman', 'Dalaman Baklavasi', 'Dalaman Cayi'),
('Mugla', 'Datça', 'Datca Baligi', 'Knidos Antik Kenti'),
('Mugla', 'Fethiye', 'Fethiye Baligi', 'Oludeniz'),
('Mugla', 'Marmaris', 'Marmaris Coregi', 'Marmaris Marina'),
('Mugla', 'Merkez', 'Milas Boregi', 'Gulluk Korfezi'),
('Mugla', 'Ortaca', 'Muðla kebabý', 'Ýztuzu Plajý'),
('Mugla', 'Ula', 'Ula pidesi', 'Sakartepe'),
('Nevþehir', 'Avanos', 'Avanos Guveci', 'Avanos Comlek Atolyeleri'),
('Nevþehir', 'Kozaklý', 'Kozakli Tarator', 'Kozakli Kaplicalari'),
('Nevþehir', 'Merkez', 'Testi Kebabi', 'Kapadokya Balon Turlari'),
('Nevþehir', 'Ürgüp', 'Urgup Sarabi', 'Goreme Acik Hava Muzesi'),
('Niðde', 'Çiftehan', 'Þekerleme', 'Bolkar Daðlarý'),
('Niðde', 'Ulukýþla', 'Börek', 'Gümüþler Manastýrý'),
('Ordu', 'Altýnordu', 'Karalahana sarmasý', 'Boztepe'),
('Ordu', 'Ünye', 'Unye Pidesi', 'Camlik Plaji'),
('Rize', 'Ýkizdere', 'Mýhlama', 'Ayder Yaylasý'),
('Rize', 'Pazar', 'Pazar Cayi', 'Pazar Kalesi'),
('Sakarya', 'Adapazarý', 'Islama köfte', 'Sakarya Nehri'),
('Sakarya', 'Sapanca', 'Manda Yogurdu', 'Sapanca Golu'),
('Sakarya', 'Serdivan', 'Serdivan Tava', 'Serdivan Parki'),
('Samsun', 'Canik', 'Pide', 'Þahinkaya Kanyonu'),
('Samsun', 'Tekkeköy', 'Çið köfte', 'Samsun Sahili'),
('Þanlýurfa', 'Eyyübiye', 'Dondurma Kebap', 'Balýklýgöl'),
('Þanlýurfa', 'Merkez', 'Fasulye', 'Göbeklitepe'),
('Sinop', 'Merkez', 'Kalkan Baligi', 'Sinop Tarihi Cezaevi'),
('Tekirdað', 'Çorlu', 'Tekirdað köftesi', 'Rüstempaþa Kervansarayý'),
('Tekirdað', 'Süleymanpaþa', 'Hayrabolu tatlýsý', 'Þehitler Abidesi'),
('Trabzon', 'Çaykara', 'Laz böreði', 'Uzungöl'),
('Trabzon', 'Merkez', 'Trabzon Pidesi', 'Ataturk Koskuy'),
('Van', 'Merkez', 'Van kahvaltýsý', 'Van Gölü'),
('Yalova', 'Altýnova', 'Yalova sütlüsü', 'Yürüyen Köþk'),
('Yalova', 'Merkez', 'Termal mýsýr ekmeði', 'Karaca Arboretumu'),
('Yalova', 'Termal', 'Termal Kebabi', 'Termal Kaplicalari'),
('Yozgat', 'Merkez', 'Yaprak sarma', 'Çamlýk Milli Parký');